#!/bin/bash
git config --global user.name "Ignacio Useche"
git config --global user.email "ignaciousecheparedes@gmail.com"
git config --global init.defaultBranch main
git config --global color.ui auto
